name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: '3.9'
      - name: install build
        run: python -m pip install -U build
      - name: build module
        run: python -m build
