name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  launch-tests:
    uses: ./.github/workflows/test.yml
    with:
      python-version: '3.10'
  build:
    uses: ./.github/workflows/build.yml
    with:
      python-version: '3.10'
    needs: launch-tests