name: Self hosted runner test

on:
  workflow_dispatch:

jobs:
  print-info:
    runs-on: self-hosted
    steps:
      - name: Print whoami
        run: whoami
      - name: Print groups
        run: groups